/**
 * GramSathi AI - Intelligent Rural Development Assistant
 * Core Application JavaScript
 */

const app = {
  // Application State
  state: {
    theme: 'light',
    language: 'English',
    profile: {
      name: 'Rural Citizen',
      role: 'Farmer',
      country: 'India',
      state: 'Maharashtra',
      district: 'Pune',
      budget: 'Small (₹50,000 - ₹2,00,000)',
      landSize: 'Small (1 - 3 Acres)',
      mainObjective: 'Agriculture & Climate Resilience'
    },
    chatHistory: [],
    activeTab: 'dashboard'
  },

  // Databases & Templates
  databases: {
    // 1. Schemes Database
    schemes: [
      {
        id: 'pm-kisan',
        name: 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)',
        category: 'Agriculture',
        tag: 'Direct Benefit Transfer',
        purpose: 'Provide income support to all landholding farmers families across the country to enable them to take care of agricultural expenses.',
        benefits: 'Direct financial benefit of ₹6,000 per year, paid in three equal installments of ₹2,000 directly into the bank accounts of the farmers.',
        eligibility: 'All landholding farmer families who own cultivable land in their names. Excludes institutional landholders, government employees, and income-tax payers.',
        documents: 'Landholding ownership papers (7/12 extract), Aadhaar Card, Bank Account Details (Passbook), Passport size photograph.',
        process: 'Register via the PM-KISAN portal (pmkisan.gov.in), through local Common Service Centers (CSCs), or via Gram Panchayat offices. Self-registration can be done using the mobile app.',
        deadlines: 'Continuous registration, payments are disbursed in April-July, August-November, and December-March cycles.',
        faqs: [
          { q: 'Is the scheme only for small and marginal farmers?', a: 'Initially yes, but it has now been extended to cover all landholding farmers regardless of landholding size.' },
          { q: 'What is a farmer family under this scheme?', a: 'A family consists of husband, wife, and minor children.' }
        ]
      },
      {
        id: 'pmfby',
        name: 'PM Fasal Bima Yojana (Crop Insurance)',
        category: 'Agriculture',
        tag: 'Crop Insurance',
        purpose: 'Provide insurance coverage and financial support to farmers in the event of failure of any of the notified crops as a result of natural calamities, pests & diseases.',
        benefits: 'Comprehensive risk insurance against crop failure with extremely low premiums: 2% for Kharif crops, 1.5% for Rabi crops, and 5% for annual commercial/horticultural crops.',
        eligibility: 'All farmers including sharecroppers and tenant farmers growing the notified crops in the notified areas are eligible.',
        documents: 'Land record documents (Aadhaar-linked), Crop sowing certificate, Bank passbook, Aadhaar card.',
        process: 'Apply online through the PMFBY portal, local banks, or common service centers. Can also be availed automatically if taking a crop loan under Kisan Credit Card (KCC).',
        deadlines: 'Kharif cut-off is usually July 31st; Rabi cut-off is usually December 31st.',
        faqs: [
          { q: 'Does it cover post-harvest losses?', a: 'Yes, it covers post-harvest losses up to a maximum period of two weeks from harvesting for crops kept in "cut and spread" condition.' },
          { q: 'How is the claim settled?', a: 'Directly credited to the bank account based on crop cutting experiments and remote sensing damage assessments.' }
        ]
      },
      {
        id: 'pmay-g',
        name: 'Pradhan Mantri Awas Yojana - Gramin',
        category: 'Housing & Water',
        tag: 'Housing Subsidy',
        purpose: 'Provide a pucca house, with basic amenities, to all houseless householders and those households living in dilapidated houses in rural areas.',
        benefits: 'Financial assistance of ₹1.2 Lakh in plains and ₹1.3 Lakh in hilly/difficult areas for house construction. Additional support of ₹12,000 for toilet construction under Swachh Bharat Mission.',
        eligibility: 'Socio-Economic and Caste Census (SECC) database driven. Prioritizes houseless, SC/ST, bonded laborers, and female-headed households.',
        documents: 'Aadhaar Card, Job Card (MGNREGA), Bank Account statement, Swachh Bharat toilet registration number.',
        process: 'Beneficiary lists are generated by the system and vetted by the Gram Sabha. Eligible citizens are notified by the Block Development Officer (BDO).',
        deadlines: 'Continuous throughout the year based on target allocations.',
        faqs: [
          { q: 'Can I construct the house anywhere?', a: 'Yes, on your own land or land allotted by the local government.' }
        ]
      },
      {
        id: 'kcc',
        name: 'Kisan Credit Card (KCC)',
        category: 'Livelihood & Loans',
        tag: 'Agricultural Credit',
        purpose: 'Provide single-window short-term credit to farmers for their cultivation needs, post-harvest expenses, consumption requirements, and maintenance of farm assets.',
        benefits: 'Low-interest loans (around 4% after prompt payment incentive). Flexible repayment schedule based on crop harvesting season. Inbuilt insurance cover.',
        eligibility: 'All farmers, joint borrowers, tenant farmers, sharecroppers, and Self-Help Groups (SHGs). Now extended to animal husbandry and fisheries.',
        documents: 'Land records, Identity proof (Aadhaar/Voter ID), Address proof, Passport size photo, No-dues certificate from nearby banks.',
        process: 'Apply at any commercial bank, cooperative bank, or Regional Rural Bank (RRB). PM-KISAN beneficiaries can get a simplified one-page application.',
        deadlines: 'Open round the year.',
        faqs: [
          { q: 'What is the credit limit?', a: 'Determined based on the crop scale of finance, acreage, and post-harvest maintenance costs.' }
        ]
      },
      {
        id: 'mudra',
        name: 'Mudra Loan Scheme (PMMY)',
        category: 'Livelihood & Loans',
        tag: 'Business Finance',
        purpose: 'Provide funding to non-corporate, non-farm small/micro enterprises to help start or expand local businesses.',
        benefits: 'Collateral-free loans up to ₹10 Lakhs categorized in three segments: Shishu (up to ₹50,000), Kishor (₹50,000 to ₹5 Lakhs), and Tarun (₹5 Lakhs to ₹10 Lakhs).',
        eligibility: 'Any Indian citizen who has a business plan for a non-farm sector income-generating activity, such as manufacturing, processing, trading, or service sector.',
        documents: 'Identity proof, Address proof, Business registration/license, Passport photos, Machinery purchase quotations or project report.',
        process: 'Apply online via Udyam Mitra portal or physically at any public/private sector bank or microfinance institution.',
        deadlines: 'No specific deadlines.',
        faqs: [
          { q: 'Is a guarantor required?', a: 'No, Mudra loans do not require collateral security or a third-party guarantor.' }
        ]
      },
      {
        id: 'ayushman',
        name: 'Ayushman Bharat (PM-JAY)',
        category: 'Health',
        tag: 'Health Insurance',
        purpose: 'Provide free health coverage at the point of service in empanelled hospitals for secondary and tertiary care hospitalization.',
        benefits: 'Cashless health insurance cover of up to ₹5 Lakh per family per year. Covers pre-existing conditions, diagnostics, and medicines.',
        eligibility: 'Identified poor and vulnerable families based on SECC 2011 indicators (e.g. landless, manual labor households).',
        documents: 'Ayushman Card, Aadhaar Card, Ration Card (for verification of family members).',
        process: 'Check eligibility on pmjay.gov.in. Visit any Ayushman Mitra kiosk at empanelled hospitals or local CSCs to generate the Ayushman Golden Card.',
        deadlines: 'Lifelong card eligibility, renews annually automatically.',
        faqs: [
          { q: 'Is there a limit on family size?', a: 'No, there is no restriction on family size or age of family members.' }
        ]
      }
    ],

    // 2. Rural Businesses Database
    businesses: [
      {
        id: 'dairy',
        name: 'Dairy Farming Business',
        icon: 'fa-cow',
        investment: '₹1.5 Lakh - ₹3 Lakh',
        profit: '₹15,000 - ₹25,000 / Month (Starts from month 2)',
        risk: 'Medium',
        demand: 'Very High (Milk and dairy products are consumed daily in both rural and urban areas)',
        skills: 'Basic livestock management, animal health check, milking, hygiene protocols',
        equipment: 'Milking buckets, animal sheds, fodder cutter, milk cans, feeding troughs',
        subsidies: 'NABARD offers 25% subsidy (33.3% for SC/ST) under the Dairy Entrepreneurship Development Scheme (DEDS).',
        steps: [
          'Purchase 2 high-yielding cows/buffaloes (e.g., Gir cow or Murrah buffalo).',
          'Construct a well-ventilated, clean cattle shed with concrete floors.',
          'Arrange continuous feed supply (dry fodder, green grass, concentrated feed).',
          'Tie up with a local dairy cooperative (e.g., Amul, Mother Dairy) or sell directly to local hotels and residents.',
          'Maintain strict vaccination and veterinary support schedule.'
        ],
        marketing: 'Establish daily delivery routes, partner with sweet shops and tea stalls, and supply directly to village dairy cooperative societies.',
        opportunities: 'Expand herd size, purchase bulk milk chillers, start selling value-added products like paneer, ghee, and curd.',
        swot: {
          s: 'Constant daily cash flow, high recurring local demand, availability of subsidies.',
          w: 'Requires 24/7 labor, high feed costs, vulnerability of cows to weather and diseases.',
          o: 'Organic manure sales, ghee/butter value addition, biogas production from cow dung.',
          t: 'Adulteration competition, price fluctuations by procurement unions.'
        }
      },
      {
        id: 'poultry',
        name: 'Backyard Poultry Farming',
        icon: 'fa-egg',
        investment: '₹40,000 - ₹80,000',
        profit: '₹8,000 - ₹12,000 / Month (Starts from month 3)',
        risk: 'Medium-High',
        demand: 'High (Eggs and poultry meat have steady demand throughout the year)',
        skills: 'Handling chicks, vaccination schedule, temperature control, bird feed mixing',
        equipment: 'Brooder heaters, feeding trays, watering bells, chicken coop netting, lighting',
        subsidies: 'NABARD and State Animal Husbandry departments offer up to 35% subsidies on setup costs.',
        steps: [
          'Set up a secure chicken coop protected from predators (dogs, snakes, birds of prey).',
          'Purchase 100-200 dual-purpose day-old chicks (e.g., Kadaknath, Vanaraja or Rhode Island Red).',
          'Maintain heating lamp conditions during the brooding period (first 3-4 weeks).',
          'Administer essential vaccinations (Ranikhet, Gumboro) to prevent disease.',
          'Sell eggs and broiler meat locally after birds reach 1.8-2kg weight.'
        ],
        marketing: 'Sell directly at weekly village markets (Haats), supply village retail stores, and tie up with local restaurants.',
        opportunities: 'Transition to certified organic free-range poultry which fetches a 50% premium price in cities.',
        swot: {
          s: 'Quick cycle (birds mature in 40-50 days), low space requirement.',
          w: 'High disease hazard (Bird Flu can wipe out stock), feed cost sensitivity.',
          o: 'High demand for country eggs, selling premium chicken breeds.',
          t: 'Dominance of corporate integrator model driving down wholesale prices.'
        }
      },
      {
        id: 'mushroom',
        name: 'Mushroom Cultivation',
        icon: 'fa-bacteria',
        investment: '₹20,000 - ₹50,000',
        profit: '₹10,000 - ₹18,000 / Month (Harvest starts in 35-45 days)',
        risk: 'Low-Medium',
        demand: 'Medium-High (Oyster and Button mushrooms are widely sought in nearby towns)',
        skills: 'Substrate sterilization, maintaining moisture and humidity (80-90%), spawning',
        equipment: 'Humidity meter, sprayers, dark grow room, shelves, crop bags, boilers for sterilization',
        subsidies: 'Horticulture Mission offers training and up to 40% subsidy for setting up grow rooms.',
        steps: [
          'Arrange a dark, clean room where temperature (20-30°C) and humidity can be controlled.',
          'Sterilize paddy straw or wheat straw by boiling or chemical treatment to kill wild fungi.',
          'Mix spawn (mushroom seed) with the sterilized straw and pack into plastic bags with holes.',
          'Hang bags in the dark room, spray water daily to maintain humidity.',
          'Harvest fresh mushrooms when caps open up, pack in ventilated packets and sell immediately.'
        ],
        marketing: 'Pack in clean 200g plastic packets. Sell to local vegetable markets, supermarkets in nearby towns, and local wedding caterers.',
        opportunities: 'Sun-dry excess harvest to produce mushroom powder or pickles, which can be stored longer and sold online.',
        swot: {
          s: 'Extremely high ROI, uses waste crop straw, vertical space utilization.',
          w: 'Requires strict cleanliness to avoid contamination, very short shelf life.',
          o: 'Growing organic gourmet mushrooms, direct-to-restaurant supply.',
          t: 'Sudden temperature spikes destroying crops without temperature control.'
        }
      },
      {
        id: 'solar',
        name: 'Solar Pump & Utility Business',
        icon: 'fa-solar-panel',
        investment: '₹1.5 Lakh - ₹2.5 Lakh',
        profit: '₹20,000 - ₹35,000 / Month',
        risk: 'Low',
        demand: 'High (Farmers require irrigation but face constant electricity cuts and high diesel costs)',
        skills: 'Basic electrical connections, solar panel maintenance, pump repair',
        equipment: 'Solar panel array, solar water pump, DC-AC inverter, transport cart, testing meters',
        subsidies: 'PM-KUSUM scheme offers up to 60% subsidy for solar pumps, with 30% bank loan options.',
        steps: [
          'Avail solar technology certification or training through PMKVY (Skill India).',
          'Purchase a mobile solar water pump set (can be loaded onto a trolley).',
          'Rent the mobile solar pump system to local farmers on an hourly/daily basis to irrigate fields.',
          'Offer solar repair, panel cleaning, and household inverter setup services in surrounding villages.',
          'Partner with solar distributors to earn commission on solar installations.'
        ],
        marketing: 'Demonstrate the solar pump in fields showing zero fuel cost compared to diesel. Give a trial hour to key farmers.',
        opportunities: 'Setup a solar-powered custom hiring center renting out tillers, cutters, and drone spraying.',
        swot: {
          s: 'Zero operating fuel cost, highly reliable, strong government support.',
          w: 'High initial capital expense, dependency on sunny days for peak water flow.',
          o: 'Selling power back to the grid (net metering), expanding to solar fence charging.',
          t: 'Theft of panels or damage during heavy hailstorms.'
        }
      },
      {
        id: 'foodproc',
        name: 'Spice & Millet Processing Unit',
        icon: 'fa-mortar-pestle',
        investment: '₹80,000 - ₹1.5 Lakh',
        profit: '₹12,000 - ₹22,000 / Month',
        risk: 'Low',
        demand: 'High (Packaged powdered spices and healthy millet flours are high-value everyday staples)',
        skills: 'Operating grinding machines, crop drying, packaging, FSSAI registration basic compliance',
        equipment: 'Pulverizer (grinding machine), weighing scale, heat sealer, sorting sieves, drying sheets',
        subsidies: 'PM Formalisation of Micro Food Processing Enterprises (PMFME) provides 35% subsidy.',
        steps: [
          'Purchase a durable commercial grinding machine (pulverizer) and sorting sieves.',
          'Procure whole raw spices (chilli, turmeric, coriander) or millets directly from local farmers.',
          'Dry, clean, and grind them into fine powders or flours.',
          'Weigh and seal them in attractive, food-grade packets with your custom brand sticker.',
          'Register for a basic FSSAI license (food safety) to supply to supermarkets and stores.'
        ],
        marketing: 'Create small budget-friendly ₹10 pouches for local village shops. Focus on pure, unadulterated marketing. Supply local school midday meals.',
        opportunities: 'Build a rural Women SHG cooperative, apply for organic certification, and sell products on e-commerce sites.',
        swot: {
          s: 'High value addition, long shelf life of products, fits home space.',
          w: 'Dust inhalation health hazard if masks aren\'t worn, price hikes of raw crops.',
          o: 'Millet-based diabetic-friendly food products, exporting to nearby districts.',
          t: 'Stiff competition from large established national spice brands.'
        }
      }
    ],

    // 3. Crops Database
    crops: {
      'Black Soil': {
        crops: [
          { name: 'Cotton (White Gold)', time: 'June - July (Kharif)', water: 'Medium (Rainfed or alternate drip)', fertilizer: 'NPK 80:40:40 kg/acre, apply in split doses.', organic: 'Incorporate 5 tons/acre Farm Yard Manure (FYM). Use Neem cake to deter sucking pests.' },
          { name: 'Soybean', time: 'Mid-June - Early July', water: 'Low-Medium (Sufficient with monsoon rains)', fertilizer: 'NPK 10:30:15 kg/acre. Seed treatment with Rhizobium is vital.', organic: 'Apply Phosphate Solubilizing Bacteria (PSB) biofertilizer.' }
        ]
      },
      'Red Soil': {
        crops: [
          { name: 'Groundnut', time: 'June (Kharif) / November (Rabi)', water: 'Low (Drought-tolerant, drains well)', fertilizer: 'NPK 10:20:30 kg/acre. Gypsum application at pegging stage is critical.', organic: 'Apply Trichoderma-treated compost to control root rot.' },
          { name: 'Ragi (Finger Millet)', time: 'June - July (Monsoon)', water: 'Very Low (Extremely climate-resilient)', fertilizer: 'NPK 24:12:12 kg/acre. Requires very minor inputs.', organic: 'Excellent crop for Zero Budget Natural Farming (ZBNF) using Jeevamrutha.' }
        ]
      },
      'Alluvial Soil': {
        crops: [
          { name: 'Rice (Paddy)', time: 'June (Sowing) - Nov (Harvest)', water: 'High (Requires standing water or system of rice intensification)', fertilizer: 'NPK 50:25:25 kg/acre. Apply Zinc Sulphate to prevent Khaira disease.', organic: 'Grow green manure (dhaincha) prior to paddy transplanting.' },
          { name: 'Wheat', time: 'November - December (Rabi)', water: 'Medium (Requires 4-6 timely irrigations)', fertilizer: 'NPK 60:30:20 kg/acre. Split nitrogen at first irrigation.', organic: 'Use Vermicompost at 2 tons/acre during land preparation.' }
        ]
      },
      'Sandy Soil': {
        crops: [
          { name: 'Bajra (Pearl Millet)', time: 'July (Kharif)', water: 'Very Low (Requires minimum rainfall)', fertilizer: 'NPK 16:8:0 kg/acre. Highly responsive to foliar spray of urea.', organic: 'Use sheep/goat folding manure to improve sandy soil texture.' },
          { name: 'Watermelon', time: 'January - February (Summer crop)', water: 'Medium (Requires drip irrigation under plastic mulch)', fertilizer: 'NPK 40:20:20 kg/acre applied through fertigation.', organic: 'Apply well-decomposed poultry manure to supply nitrogen.' }
        ]
      }
    }
  },

  // Initialize Application
  init: function() {
    this.loadState();
    this.setupEventListeners();
    this.checkOnboarding();
    this.updateDashboardOverview();
    this.renderSchemesCatalog();
    this.renderBusinessList();
    this.simulateWeather();
    
    // Auto-scroll chat body
    this.scrollChat();
  },

  // State Management (LocalStorage)
  loadState: function() {
    const savedTheme = localStorage.getItem('gramsathi_theme');
    if (savedTheme) {
      this.state.theme = savedTheme;
      document.documentElement.setAttribute('data-theme', savedTheme);
      const icon = document.querySelector('#themeToggleBtn i');
      if (icon) {
        icon.className = savedTheme === 'dark' ? 'fa-solid fa-sun' : 'fa-solid fa-moon';
      }
    }

    const savedLang = localStorage.getItem('gramsathi_lang');
    if (savedLang) {
      this.state.language = savedLang;
      document.getElementById('langSelector').value = savedLang;
      document.getElementById('wizardLanguage').value = savedLang;
      document.getElementById('settingsLanguage').value = savedLang;
    }

    const savedProfile = localStorage.getItem('gramsathi_profile');
    if (savedProfile) {
      this.state.profile = JSON.parse(savedProfile);
      this.applyProfileToUI();
    }
  },

  saveProfileState: function(newProfile) {
    this.state.profile = { ...this.state.profile, ...newProfile };
    localStorage.setItem('gramsathi_profile', JSON.stringify(this.state.profile));
    this.applyProfileToUI();
    this.updateDashboardOverview();
    this.simulateWeather();
  },

  applyProfileToUI: function() {
    // Update Sidebar display
    document.getElementById('sidebarUserName').textContent = this.state.profile.name || 'Rural Citizen';
    document.getElementById('sidebarUserRole').textContent = this.state.profile.role || 'Farmer';
    document.getElementById('sidebarAvatar').textContent = (this.state.profile.name || 'U').charAt(0).toUpperCase();

    // Populate Settings Form fields
    document.getElementById('settingsName').value = this.state.profile.name || '';
    document.getElementById('settingsRole').value = this.state.profile.role || 'Farmer';
    document.getElementById('settingsState').value = this.state.profile.state || '';
    document.getElementById('settingsDistrict').value = this.state.profile.district || '';
    document.getElementById('settingsBudget').value = this.state.profile.budget || '';
    document.getElementById('settingsLand').value = this.state.profile.landSize || '';
  },

  // Onboarding Setup Wizard Controls
  checkOnboarding: function() {
    const isCompleted = localStorage.getItem('gramsathi_onboarded');
    if (isCompleted === 'true') {
      document.getElementById('onboardingOverlay').style.display = 'none';
    } else {
      document.getElementById('onboardingOverlay').style.display = 'flex';
      this.setupWizardPanes();
    }
  },

  setupWizardPanes: function() {
    let currentStep = 1;
    const panes = [document.getElementById('pane1'), document.getElementById('pane2'), document.getElementById('pane3')];
    const indicators = [document.getElementById('stepIndicator1'), document.getElementById('stepIndicator2'), document.getElementById('stepIndicator3')];
    const nextBtn = document.getElementById('wizardNextBtn');
    const backBtn = document.getElementById('wizardBackBtn');

    const updateWizardUI = () => {
      panes.forEach((pane, idx) => {
        pane.classList.toggle('active', idx === currentStep - 1);
      });
      indicators.forEach((indicator, idx) => {
        indicator.classList.toggle('active', idx < currentStep);
      });

      backBtn.style.visibility = currentStep === 1 ? 'hidden' : 'visible';
      if (currentStep === 3) {
        nextBtn.innerHTML = 'Finish <i class="fa-solid fa-check"></i>';
      } else {
        nextBtn.innerHTML = 'Next <i class="fa-solid fa-arrow-right"></i>';
      }
    };

    nextBtn.onclick = () => {
      if (currentStep < 3) {
        currentStep++;
        updateWizardUI();
      } else {
        // Gather and save onboarding data
        const profileData = {
          name: document.getElementById('wizardUserRole').value === 'Student' ? 'Akshay Sagar' : 'Farmer Akshay',
          role: document.getElementById('wizardUserRole').value,
          country: document.getElementById('wizardCountry').value,
          state: document.getElementById('wizardState').value || 'Maharashtra',
          district: document.getElementById('wizardDistrict').value || 'Pune',
          budget: document.getElementById('wizardBudget').value,
          landSize: document.getElementById('wizardLand').value,
          mainObjective: document.getElementById('wizardInterest').value
        };
        
        localStorage.setItem('gramsathi_onboarded', 'true');
        this.saveProfileState(profileData);
        document.getElementById('onboardingOverlay').style.display = 'none';
        this.showToast('Profile personalized successfully! Welcome to GramSathi AI.', 'success');
      }
    };

    backBtn.onclick = () => {
      if (currentStep > 1) {
        currentStep--;
        updateWizardUI();
      }
    };
  },

  // Simulated Weather Generation
  simulateWeather: function() {
    const district = this.state.profile.district || 'Pune';
    const state = this.state.profile.state || 'Maharashtra';
    
    // Static lists for variety
    const conditions = ['Sunny', 'Clear', 'Drizzle', 'Overcast', 'Humid'];
    const selectedCondition = conditions[Math.floor(Math.random() * conditions.length)];
    const temp = Math.floor(Math.random() * (35 - 22 + 1)) + 22; // 22 to 35
    
    const weatherText = `${district}, ${state}: ${selectedCondition}, ${temp}°C`;
    document.getElementById('weatherText').textContent = weatherText;
  },

  // Router & Navigation Tabs
  setupEventListeners: function() {
    const sidebarItems = document.querySelectorAll('.nav-links .nav-item');
    const sections = document.querySelectorAll('.content-area .tab-panel');

    sidebarItems.forEach(item => {
      item.onclick = (e) => {
        e.preventDefault();
        const tab = item.getAttribute('data-tab');
        
        // Remove active class
        sidebarItems.forEach(i => i.classList.remove('active'));
        sections.forEach(s => s.classList.remove('active'));

        // Add active class to clicked item and matched panel
        item.classList.add('active');
        const activeSection = document.getElementById(`tab-${tab}`);
        if (activeSection) activeSection.classList.add('active');

        // Update Title in Header
        const displayTitles = {
          dashboard: 'Dashboard',
          chat: 'GramSathi AI Chat Assistant',
          schemes: 'Government Welfare Schemes',
          farming: 'Farm & Climate Hub',
          business: 'Rural Entrepreneurship Planner',
          proposal: 'Panchayat & NGO Project Proposals',
          disaster: 'Resilience & Safety Center',
          settings: 'Profile Settings'
        };
        document.getElementById('headerTitle').textContent = displayTitles[tab] || 'Dashboard';
        this.state.activeTab = tab;
        
        // Close sidebar on mobile
        document.getElementById('appSidebar').classList.remove('active');
      };
    });

    // Theme Toggle
    document.getElementById('themeToggleBtn').onclick = () => {
      const current = document.documentElement.getAttribute('data-theme');
      const target = current === 'dark' ? 'light' : 'dark';
      document.documentElement.setAttribute('data-theme', target);
      localStorage.setItem('gramsathi_theme', target);
      this.state.theme = target;
      
      const icon = document.querySelector('#themeToggleBtn i');
      icon.className = target === 'dark' ? 'fa-solid fa-sun' : 'fa-solid fa-moon';
      this.showToast(`Switched to ${target} theme`, 'info');
    };

    // Language Dropdown Selector
    document.getElementById('langSelector').onchange = (e) => {
      const lang = e.target.value;
      localStorage.setItem('gramsathi_lang', lang);
      this.state.language = lang;
      this.showToast(`Language set to ${lang}`, 'info');
    };

    // Menu Mobile toggle
    document.getElementById('menuToggle').onclick = () => {
      document.getElementById('appSidebar').classList.add('active');
    };

    // Relaunch wizard
    document.getElementById('relaunchWizardBtn').onclick = () => {
      localStorage.setItem('gramsathi_onboarded', 'false');
      this.checkOnboarding();
    };

    // Save Settings
    document.getElementById('saveSettingsBtn').onclick = () => {
      const profileData = {
        name: document.getElementById('settingsName').value,
        role: document.getElementById('settingsRole').value,
        state: document.getElementById('settingsState').value,
        district: document.getElementById('settingsDistrict').value,
        budget: document.getElementById('settingsBudget').value,
        landSize: document.getElementById('settingsLand').value,
        language: document.getElementById('settingsLanguage').value
      };
      
      this.saveProfileState(profileData);
      this.showToast('Profile adjustments saved successfully!', 'success');
    };

    // Reset wizard button
    document.getElementById('resetWizardBtn').onclick = () => {
      localStorage.removeItem('gramsathi_onboarded');
      localStorage.removeItem('gramsathi_profile');
      window.location.reload();
    };

    // Search Government Schemes
    document.getElementById('schemeSearchInput').oninput = () => {
      this.renderSchemesCatalog();
    };
    document.getElementById('schemeCategoryFilter').onchange = () => {
      this.renderSchemesCatalog();
    };

    // Modal Close
    document.getElementById('modalCloseBtn').onclick = () => {
      document.getElementById('schemeModal').classList.remove('active');
    };

    // Chat Interface Actions
    document.getElementById('chatSendBtn').onclick = () => {
      this.handleUserChatMessage();
    };
    document.getElementById('chatInput').onkeypress = (e) => {
      if (e.key === 'Enter') {
        this.handleUserChatMessage();
      }
    };

    // Chat Suggestion Chips
    document.querySelectorAll('.suggestion-chip').forEach(chip => {
      chip.onclick = () => {
        const promptText = chip.getAttribute('data-prompt');
        document.getElementById('chatInput').value = promptText;
        this.handleUserChatMessage();
      };
    });

    // Farm Recommendations Calculator
    document.getElementById('calculateCropsBtn').onclick = () => {
      this.calculateFarmCrops();
    };

    // Proposal Generator Actions
    document.getElementById('generateProposalBtn').onclick = () => {
      this.generateProposalReport();
    };
    document.getElementById('copyProposalBtn').onclick = () => {
      const text = document.getElementById('proposalOutputBody').textContent;
      navigator.clipboard.writeText(text);
      this.showToast('Proposal copied to clipboard!', 'success');
    };
    document.getElementById('printProposalBtn').onclick = () => {
      window.print();
    };

    // Disaster Center Actions
    document.querySelectorAll('.disaster-btn').forEach(btn => {
      btn.onclick = () => {
        document.querySelectorAll('.disaster-btn').forEach(b => b.classList.remove('active'));
        btn.classList.add('active');
        const hazard = btn.getAttribute('data-hazard');
        this.renderDisasterDetails(hazard);
      };
    });
    this.renderDisasterDetails('flood'); // default load
  },

  // Helper: Toast Notifications
  showToast: function(message, type = 'info') {
    const container = document.getElementById('toastContainer');
    const toast = document.createElement('div');
    toast.className = `toast ${type}`;
    
    let iconClass = 'fa-circle-info';
    if (type === 'success') iconClass = 'fa-circle-check';
    if (type === 'danger') iconClass = 'fa-triangle-exclamation';

    toast.innerHTML = `<i class="fa-solid ${iconClass}"></i> <span>${message}</span>`;
    container.appendChild(toast);

    setTimeout(() => {
      toast.style.opacity = '0';
      setTimeout(() => {
        toast.remove();
      }, 300);
    }, 4000);
  },

  // Dashboard State Refresh
  updateDashboardOverview: function() {
    const p = this.state.profile;
    const cropText = p.landSize === 'None / Landless' ? 'No land owned' : 'Groundnut / Rice';
    document.getElementById('dashRecommendedCrop').textContent = cropText;
    
    // Recommended business based on budget
    let bizName = 'Mushroom Farming';
    if (p.budget.includes('Micro')) bizName = 'Mushroom Cultivation';
    else if (p.budget.includes('Small')) bizName = 'Backyard Poultry';
    else if (p.budget.includes('Medium')) bizName = 'Spice Processing';
    else bizName = 'Dairy Farming';
    
    document.getElementById('dashBusinessOption').textContent = bizName;

    // Direct advice text block
    const overviewDiv = document.getElementById('dashboardOverviewText');
    overviewDiv.innerHTML = `
      <p style="margin-bottom: 8px;">Hello, <strong>${p.name || 'Akshay Sagar'}</strong>. Based on your profile setup as a <strong>${p.role}</strong> located in <strong>${p.district}, ${p.state}</strong>, GramSathi AI has pre-loaded relevant datasets.</p>
      <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; margin-top: 16px;">
        <div style="background: var(--bg-primary); padding: 12px; border-radius: var(--radius-sm);">
          <span style="font-size: 0.75rem; color: var(--text-secondary); text-transform: uppercase; font-weight: 600; display:block;">Target Budget</span>
          <strong>${p.budget}</strong>
        </div>
        <div style="background: var(--bg-primary); padding: 12px; border-radius: var(--radius-sm);">
          <span style="font-size: 0.75rem; color: var(--text-secondary); text-transform: uppercase; font-weight: 600; display:block;">Target Area / Land</span>
          <strong>${p.landSize}</strong>
        </div>
      </div>
    `;
  },

  // 1. Chat Assistant Logic (Custom 10-part generator)
  scrollChat: function() {
    const chatBody = document.getElementById('chatBody');
    chatBody.scrollTop = chatBody.scrollHeight;
  },

  handleUserChatMessage: function() {
    const chatInput = document.getElementById('chatInput');
    const queryText = chatInput.value.trim();
    if (!queryText) return;

    // Clear user input
    chatInput.value = '';

    // Append User Message
    this.appendMessage('user', queryText);
    this.scrollChat();

    // Show AI "Thinking..." block
    const thinkingId = 'thinking-' + Date.now();
    this.appendMessage('ai', `<i class="fa-solid fa-spinner fa-spin"></i> GramSathi AI is analyzing rural databases...`, thinkingId);
    this.scrollChat();

    setTimeout(() => {
      // Remove thinking indicator
      document.getElementById(thinkingId).remove();

      // Generate structured response
      const responseHtml = this.generateGramSathiResponse(queryText);
      this.appendMessage('ai', responseHtml);
      this.scrollChat();
    }, 1200);
  },

  appendMessage: function(sender, content, id = '') {
    const chatBody = document.getElementById('chatBody');
    
    // Remove welcome pane if still present
    const welcome = chatBody.querySelector('.chat-welcome');
    if (welcome) welcome.remove();

    const messageDiv = document.createElement('div');
    messageDiv.className = `message ${sender}`;
    if (id) messageDiv.id = id;

    const avatar = document.createElement('div');
    avatar.className = 'chat-header-avatar';
    avatar.textContent = sender === 'user' ? 'U' : 'GS';
    if (sender === 'user') {
      avatar.textContent = (this.state.profile.name || 'U').charAt(0).toUpperCase();
      avatar.style.background = 'var(--primary-hover)';
    }

    const bubble = document.createElement('div');
    bubble.className = 'msg-bubble';
    bubble.innerHTML = content;

    messageDiv.appendChild(avatar);
    messageDiv.appendChild(bubble);
    chatBody.appendChild(messageDiv);
  },

  generateGramSathiResponse: function(query) {
    const q = query.toLowerCase();
    const p = this.state.profile;

    // Check pre-configured response matches
    if (q.includes('crop') || q.includes('black soil') || q.includes('red soil') || q.includes('soil')) {
      return this.templates.cropAdvice(p.district, p.state, p.landSize);
    }
    
    if (q.includes('business') || q.includes('lakh') || q.includes('entrepreneur') || q.includes('dairy') || q.includes('mushroom')) {
      return this.templates.businessAdvice(p.budget);
    }

    if (q.includes('kisan') || q.includes('pm-kisan') || q.includes('scheme') || q.includes('welfare') || q.includes('eligible')) {
      return this.templates.pmKisanDetails();
    }

    if (q.includes('dairy farm') || q.includes('dairy farming project') || q.includes('project report')) {
      return this.templates.dairyProjectReport(p.district, p.state);
    }

    // Fallback: A highly structured, dynamic 10-part report matching the system guidelines
    return this.templates.genericTemplate(query, p.district, p.state, p.role);
  },

  // HTML templates for 10-Part Standard Response
  templates: {
    // 1. Soil & Crop Response
    cropAdvice: function(district, state, landSize) {
      return `
        <div class="ai-structured-response">
          <div class="response-section">
            <div class="response-section-title">1. Summary</div>
            <div class="response-section-content">
              Recommendations for crop cultivation on black cotton soil in ${district}, ${state} for a ${landSize} field. We focus on maximizing yields using climate-smart moisture conservation strategies.
            </div>
          </div>
          
          <div class="response-section">
            <div class="response-section-title">2. Detailed Explanation</div>
            <div class="response-section-content">
              Black soil (Vertisol) has high clay content, providing excellent water retention but making it sticky when wet and cracking deep when dry. During dry conditions, you must focus on crops with deep taproots or short durations to escape drought stress. Ideal options are <strong>Cotton (Kharif)</strong> or <strong>Soybean</strong> intercropped with Pigeon Pea.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">3. Benefits</div>
            <div class="response-section-content">
              - **Moisture Efficiency:** Retains crop root zone water during short dry-spells.<br>
              - **Market Integrity:** Cotton and Soybean have guaranteed Minimum Support Price (MSP) purchase centers across ${state}.<br>
              - **Soil Health:** Intercropping leguminous pigeon pea fixes atmospheric nitrogen.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">4. Challenges</div>
            <div class="response-section-content">
              - Poor aeration and waterlogging during heavy monsoon rains.<br>
              - High vulnerability to sucking pests (Aphids, Jassids) and Cotton Pink Bollworm.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">5. Step-by-Step Process</div>
            <div class="response-section-content">
              1. **Land Preparation:** Deep ploughing during summer to expose pest cocoons.<br>
              2. **Seed Treatment:** Treat seeds with Imidacloprid (pest deterrence) and Trichoderma (root rot control).<br>
              3. **Sowing:** Sow on a Broad Bed Furrow (BBF) layout to allow drainage.<br>
              4. **Weeding:** Manual hand hoeing at 20 and 45 days.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">6. Real-Life Example</div>
            <div class="response-section-content">
              Shri Ramrao Patil, a farmer in Pune district, adopted BBF sowing on 3 acres of black soil. In spite of delayed monsoon rains, his soybean yields increased by 22% compared to traditional flat-bed broadcasting.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">7. Best Practices</div>
            <div class="response-section-content">
              - Construct farm ponds for rainwater harvesting and emergency life-saving watering.<br>
              - Apply gypsum to improve soil aeration and physical soil structure.
            </div>
          </div>

          <div class="response-section alert-section">
            <div class="response-section-title"><i class="fa-solid fa-indian-rupee-sign"></i> 8. Government Support</div>
            <div class="response-section-content">
              Subsidies up to 50% are available for BBF sowing machines under the Sub-Mission on Agricultural Mechanization (SMAM). PM Fasal Bima Yojana offers crop insurance at just 2% premium.
            </div>
          </div>

          <div class="response-section alert-section">
            <div class="response-section-title"><i class="fa-solid fa-triangle-exclamation"></i> 9. Common Mistakes</div>
            <div class="response-section-content">
              - **Over-irrigation:** Causes root rot (wilt) due to soil waterlogging.<br>
              - **Late Sowing:** Exposes mature cotton to winter fog, attracting Pink Bollworm.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">10. Final Recommendation</div>
            <div class="response-section-content">
              <strong>Recommendation:</strong> Get a free soil card test from the nearest Krishi Vigyan Kendra (KVK). Adopt a Soybean + Pigeon Pea (4:2 ratio) intercropping system with Drip irrigation under government subsidy.
            </div>
          </div>
        </div>
      `;
    },

    // 2. Rural Business Response
    businessAdvice: function(budget) {
      return `
        <div class="ai-structured-response">
          <div class="response-section">
            <div class="response-section-title">1. Summary</div>
            <div class="response-section-content">
              Business startup recommendation customized for your budget category: <strong>${budget}</strong>. We suggest starting a **Spice & Food Processing Unit** or **Oyster Mushroom cultivation**.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">2. Detailed Explanation</div>
            <div class="response-section-content">
              For investments under ₹1 Lakh, micro food processing is highly profitable. Raw spices (Chilli, Turmeric, Coriander) can be purchased cheaply from local weekly markets, ground locally using a mini pulverizer machine, and packed into branded packets.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">3. Benefits</div>
            <div class="response-section-content">
              - **High Margins:** Added-value processing turns raw crops into products fetching up to 40% gross margins.<br>
              - **No Perishability:** Packaged spice powders can be stored for 6-9 months.<br>
              - **Flexible Space:** Can easily be operated from a small clean room at home.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">4. Challenges</div>
            <div class="response-section-content">
              - Securing an FSSAI Food Safety license (required to sell in retail stores).<br>
              - Competing with large, established commercial spice brands.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">5. Step-by-Step Process</div>
            <div class="response-section-content">
              1. **Procurement:** Buy 100 kg of dried whole spices from wholesale traders.<br>
              2. **Grinding:** Grind into fine powders using a commercial 2 HP pulverizer.<br>
              3. **Packaging:** Weigh into 100g/250g pouches and seal using a heat sealing machine.<br>
              4. **Marketing:** Distribute sample pouches to local tea shops and provision stores.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">6. Real-Life Example</div>
            <div class="response-section-content">
              The 'Savitribai SHG' in Satara district started a spice grinding micro-enterprise with a capital of ₹60,000. Within 6 months, they reached a monthly net profit of ₹18,000 by packaging "Ghar ka Masala."
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">7. Best Practices</div>
            <div class="response-section-content">
              - Ensure absolute cleanliness. Even minor dampness will ruin spice batches.<br>
              - Use food-grade, airtight plastic packaging to lock in freshness.
            </div>
          </div>

          <div class="response-section alert-section">
            <div class="response-section-title"><i class="fa-solid fa-indian-rupee-sign"></i> 8. Government Support</div>
            <div class="response-section-content">
              Under the **PMFME Scheme**, you can avail of a 35% credit-linked capital subsidy. Women SHGs can secure zero-interest revolving funds up to ₹50,000 from the State Rural Livelihoods Mission (SRLM).
            </div>
          </div>

          <div class="response-section alert-section">
            <div class="response-section-title"><i class="fa-solid fa-triangle-exclamation"></i> 9. Common Mistakes</div>
            <div class="response-section-content">
              - Failing to double-check weight calibration (leading to consumer complaints).<br>
              - Packing spices before they cool down from grinding (creates moisture inside).
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">10. Final Recommendation</div>
            <div class="response-section-content">
              <strong>Recommendation:</strong> Register under Udyam (MSME) for free, purchase a semi-automatic pulverizer, and focus on selling to local dhabas and schools first before scaling up.
            </div>
          </div>
        </div>
      `;
    },

    // 3. PM Kisan Scheme Response
    pmKisanDetails: function() {
      return `
        <div class="ai-structured-response">
          <div class="response-section">
            <div class="response-section-title">1. Summary</div>
            <div class="response-section-content">
              Detailed handbook for the **Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)** welfare scheme, designed to support farm income nationwide.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">2. Detailed Explanation</div>
            <div class="response-section-content">
              PM-KISAN is a central sector scheme. It provides an annual cash benefit of ₹6,000, disbursed in three installments of ₹2,000 every four months directly to Aadhaar-seeded bank accounts of land-holding agricultural families.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">3. Benefits</div>
            <div class="response-section-content">
              - **Direct Cash Transfer:** No middlemen; direct bank credit.<br>
              - **Timely Support:** Cash is released before planting seasons (Kharif, Rabi, Summer) to help buy seeds and fertilizers.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">4. Challenges</div>
            <div class="response-section-content">
              - Verification delays at the state revenue department level.<br>
              - Transaction failures due to mismatch of name spellings in Bank passbooks and Aadhaar.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">5. Step-by-Step Process</div>
            <div class="response-section-content">
              1. **Check Eligibility:** Own cultivable land. Family includes spouse and minors.<br>
              2. **Self-Registration:** Visit the PM-KISAN portal (pmkisan.gov.in) -> "Farmers Corner" -> "New Farmer Registration".<br>
              3. **Aadhaar Verification:** Enter Aadhaar and mobile number, verify OTP.<br>
              4. **Data Input:** Fill in land details (Khata number, Survey/Khasra number) and upload land papers.<br>
              5. **Approval:** Track status online; localized approval will be done by the Tehsildar or Nodal Officer.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">6. Real-Life Example</div>
            <div class="response-section-content">
              Smt. Meerabai, a marginal farmer, completed the name mismatch correction on her Aadhaar at the local Gram Panchayat office. Within 15 days, her pending installments were cleared and credited.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">7. Best Practices</div>
            <div class="response-section-content">
              - Complete your **eKYC** immediately using the face-authentication feature on the PM-KISAN mobile application.<br>
              - Ensure the bank account is linked to Aadhaar and NPCI mapping is active.
            </div>
          </div>

          <div class="response-section alert-section">
            <div class="response-section-title"><i class="fa-solid fa-indian-rupee-sign"></i> 8. Government Support</div>
            <div class="response-section-content">
              Common Service Centers (CSCs) are authorized to assist with applications for a nominal fee of ₹15.
            </div>
          </div>

          <div class="response-section alert-section">
            <div class="response-section-title"><i class="fa-solid fa-triangle-exclamation"></i> 9. Common Mistakes</div>
            <div class="response-section-content">
              - Expatriates, institutional landowners, and families where a member pays income tax are ineligible. Applying leads to blacklisting and recovery demands.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">10. Final Recommendation</div>
            <div class="response-section-content">
              <strong>Recommendation:</strong> Visit the official web portal to verify if your status indicates 'Aadhaar Seeded: YES'. If you face issues, submit a grievance ticket under the PM-KISAN Helpdesk.
            </div>
          </div>
        </div>
      `;
    },

    // 4. Dairy Project Report
    dairyProjectReport: function(district, state) {
      return `
        <div class="ai-structured-response">
          <div class="response-section">
            <div class="response-section-title">1. Summary</div>
            <div class="response-section-content">
              Project report for starting a **2-Animal Dairy Farming Unit** in ${district}, ${state} with capital estimation, daily returns, and SWOT indicators.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">2. Detailed Explanation</div>
            <div class="response-section-content">
              A 2-animal dairy farm (Murrah Buffaloes or crossbred cows) is the ideal start-up size. It allows for continuous milk production (if one animal is in lactation while the other is dry). Average milk yield expected is 10-12 Liters per animal per day.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">3. Cost & Benefit Table</div>
            <div class="response-section-content">
              <table class="response-table">
                <thead>
                  <tr>
                    <th>Item Description</th>
                    <th>Quantity/Cost</th>
                    <th>Recurring monthly cost</th>
                    <th>Expected revenue</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Purchase of 2 Animals</td>
                    <td>₹1,40,000</td>
                    <td>-</td>
                    <td>-</td>
                  </tr>
                  <tr>
                    <td>Shed Construction</td>
                    <td>₹35,000</td>
                    <td>-</td>
                    <td>-</td>
                  </tr>
                  <tr>
                    <td>Feed (Concentrate + Fodder)</td>
                    <td>-</td>
                    <td>₹8,000 / month</td>
                    <td>-</td>
                  </tr>
                  <tr>
                    <td>Milk Sales (20 Liters @ ₹50/L)</td>
                    <td>-</td>
                    <td>-</td>
                    <td>₹30,000 / month</td>
                  </tr>
                </tbody>
              </table>
              <p style="margin-top: 8px; font-weight: bold; color: var(--success);">Net Profit: ~₹18,000 - ₹20,000 per month (after feed & medicine costs)</p>
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">4. Challenges</div>
            <div class="response-section-content">
              - Maintaining green fodder supply during dry summer months.<br>
              - Immediate drop in milk yield if animals are stressed by heat or foot-and-mouth disease (FMD).
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">5. Step-by-Step Process</div>
            <div class="response-section-content">
              1. **Animal Procurement:** Purchase animals from certified livestock markets. Ensure they have milk record proof.<br>
              2. **Shed Setup:** Floor must be slip-resistant with a 1.5% slope for urine drainage.<br>
              3. **Fodder:** Plant Napier grass or fodder maize on a small plot (0.5 acres).<br>
              4. **Cooperative Tie-up:** Register with the local dairy collection center to guarantee daily sales.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">6. Real-Life Example</div>
            <div class="response-section-content">
              Sandeep Pawar in Haveli Taluka began with 2 cows. By selling dung as organic fertilizer to local vineyards and supplying milk to the cooperative, he paid off his initial loan in 18 months.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">7. SWOT Analysis</div>
            <div class="response-section-content">
              - **Strengths:** Constant demand, high subsidy availability (NABARD).<br>
              - **Weaknesses:** Highly labor-intensive, requires daily discipline.<br>
              - **Opportunities:** Processing curd/ghee for premium urban sales.<br>
              - **Threats:** Fodder price hikes, contagious disease outbreaks.
            </div>
          </div>

          <div class="response-section alert-section">
            <div class="response-section-title"><i class="fa-solid fa-indian-rupee-sign"></i> 8. Government Support</div>
            <div class="response-section-content">
              Under the **Animal Husbandry Infrastructure Development Fund (AHIDF)**, farmers get a 3% interest subvention on loans. Get zero-interest animal loans under Kisan Credit Card (KCC) up to ₹2 Lakh.
            </div>
          </div>

          <div class="response-section alert-section">
            <div class="response-section-title"><i class="fa-solid fa-triangle-exclamation"></i> 9. Common Mistakes</div>
            <div class="response-section-content">
              - Buying old animals or animals without veterinary certificates.<br>
              - Keeping the cattle shed damp (leads to Mastitis disease).
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">10. Final Recommendation</div>
            <div class="response-section-content">
              <strong>Recommendation:</strong> Start with two crossbred cows (HF/Jersey crosses) or Murrah Buffaloes. Avail of a KCC livestock loan from your local cooperative bank to secure interest subsidies.
            </div>
          </div>
        </div>
      `;
    },

    // 5. Generic Fallback Response
    genericTemplate: function(query, district, state, role) {
      return `
        <div class="ai-structured-response">
          <div class="response-section">
            <div class="response-section-title">1. Summary</div>
            <div class="response-section-content">
              GramSathi AI analysis for the query: "${query}" tailored for a <strong>${role}</strong> in <strong>${district}, ${state}</strong>.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">2. Detailed Explanation</div>
            <div class="response-section-content">
              Your request regarding "${query}" touches upon local livelihood planning. GramSathi AI recommends aligning your plans with the state policies of ${state} and leveraging district-level agricultural offices (Krishi Bhavan) or cooperative societies.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">3. Benefits</div>
            <div class="response-section-content">
              - **Livelihood Security:** Improves local household income.<br>
              - **Skill Utilization:** Promotes local village craftsmanship or farming practices.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">4. Challenges</div>
            <div class="response-section-content">
              - Access to credit and capital startup loans.<br>
              - High cost of raw inputs and transport logistics in rural zones.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">5. Step-by-Step Process</div>
            <div class="response-section-content">
              1. Formulate a basic business layout or project plan.<br>
              2. Visit your local Panchayat office to check for matching subsidies.<br>
              3. Procure quality certified inputs locally.<br>
              4. Document costs and yields/outputs daily.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">6. Real-Life Example</div>
            <div class="response-section-content">
              A farmers' group in neighboring district adopted community-based resource sharing for similar projects, saving 20% on transportation and logistics.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">7. Best Practices</div>
            <div class="response-section-content">
              - Focus on sustainable, low-water, and organic practices.<br>
              - Maintain clear paper records for audit or loan clearance.
            </div>
          </div>

          <div class="response-section alert-section">
            <div class="response-section-title"><i class="fa-solid fa-indian-rupee-sign"></i> 8. Government Support</div>
            <div class="response-section-content">
              Consult state-specific portals like MAHADBT (for Maharashtra) or equivalents to apply for agricultural inputs and subsidies directly.
            </div>
          </div>

          <div class="response-section alert-section">
            <div class="response-section-title"><i class="fa-solid fa-triangle-exclamation"></i> 9. Common Mistakes</div>
            <div class="response-section-content">
              - Taking loans from unverified informal money-lenders at high interest rates. Always use public cooperative banks.
            </div>
          </div>

          <div class="response-section">
            <div class="response-section-title">10. Final Recommendation</div>
            <div class="response-section-content">
              <strong>Recommendation:</strong> Join or form a Farmer Producer Organisation (FPO) or Self-Help Group (SHG) to access collective bargain pricing and group loan products.
            </div>
          </div>
        </div>
      `;
    }
  },

  // 2. Government Schemes catalog rendering
  renderSchemesCatalog: function() {
    const searchVal = document.getElementById('schemeSearchInput').value.toLowerCase();
    const catVal = document.getElementById('schemeCategoryFilter').value;
    const grid = document.getElementById('schemesGrid');
    grid.innerHTML = '';

    const filtered = this.databases.schemes.filter(s => {
      const matchSearch = s.name.toLowerCase().includes(searchVal) || 
                          s.purpose.toLowerCase().includes(searchVal) || 
                          s.eligibility.toLowerCase().includes(searchVal);
      const matchCat = catVal === 'ALL' || s.category === catVal;
      return matchSearch && matchCat;
    });

    if (filtered.length === 0) {
      grid.innerHTML = `<div style="grid-column: 1/-1; text-align: center; color: var(--text-secondary); padding: 40px;">No matching schemes found. Adjust search terms.</div>`;
      return;
    }

    filtered.forEach(s => {
      const card = document.createElement('div');
      card.className = 'scheme-card';
      card.onclick = () => this.showSchemeModal(s.id);

      card.innerHTML = `
        <div>
          <span class="scheme-tag">${s.category}</span>
          <h3 class="scheme-title">${s.name}</h3>
          <p class="scheme-desc">${s.purpose}</p>
        </div>
        <div class="scheme-meta">
          <span><i class="fa-solid fa-user-check"></i> Check Eligibility</span>
          <span><i class="fa-solid fa-arrow-right"></i></span>
        </div>
      `;
      grid.appendChild(card);
    });

    // Update stats count on dashboard
    document.getElementById('dashSchemesCount').textContent = `${filtered.length} Available`;
  },

  showSchemeModal: function(id) {
    const s = this.databases.schemes.find(item => item.id === id);
    if (!s) return;

    const content = document.getElementById('modalContent');
    content.innerHTML = `
      <div class="scheme-detail-header">
        <span class="scheme-tag">${s.category}</span>
        <h3 class="scheme-detail-title">${s.name}</h3>
        <p style="color: var(--text-secondary); font-size: 0.85rem; margin-top: 4px;">Category: ${s.tag}</p>
      </div>

      <div class="scheme-section">
        <h4><i class="fa-solid fa-circle-info"></i> Purpose</h4>
        <p>${s.purpose}</p>
      </div>

      <div class="scheme-section">
        <h4><i class="fa-solid fa-gift"></i> Scheme Benefits</h4>
        <p>${s.benefits}</p>
      </div>

      <div class="scheme-section">
        <h4><i class="fa-solid fa-user-check"></i> Eligibility Criteria</h4>
        <p>${s.eligibility}</p>
      </div>

      <div class="scheme-section">
        <h4><i class="fa-solid fa-file-invoice"></i> Required Documents</h4>
        <p>${s.documents}</p>
      </div>

      <div class="scheme-section">
        <h4><i class="fa-solid fa-circle-play"></i> Application Process</h4>
        <p>${s.process}</p>
      </div>

      <div class="scheme-section">
        <h4><i class="fa-solid fa-calendar-days"></i> Important Timelines & Deadlines</h4>
        <p>${s.deadlines}</p>
      </div>

      <div class="scheme-section">
        <h4><i class="fa-solid fa-circle-question"></i> Frequently Asked Questions</h4>
        <ul>
          ${s.faqs.map(faq => `<li><strong>Q: ${faq.q}</strong><br>A: ${faq.a}</li>`).join('')}
        </ul>
      </div>
    `;

    document.getElementById('schemeModal').classList.add('active');
  },

  // 3. Farm Hub Crop & Irrigation calculation
  calculateFarmCrops: function() {
    const soil = document.getElementById('soilTypeSelect').value;
    const water = document.getElementById('waterSourceSelect').value;
    
    const cropData = this.databases.crops[soil];
    const outputDiv = document.getElementById('farmResultContent');
    const initialText = document.getElementById('farmResultInitialText');

    if (!cropData) return;

    initialText.style.display = 'none';
    outputDiv.style.display = 'block';

    let cropsHtml = '';
    cropData.crops.forEach(c => {
      cropsHtml += `
        <div style="border-bottom: 1px solid var(--border-color); padding-bottom: 16px; margin-bottom: 16px;">
          <h4 style="font-family: var(--font-display); font-size: 1.1rem; color: var(--primary-hover); display: flex; align-items: center; gap: 8px;">
            <i class="fa-solid fa-seedling"></i> ${c.name}
          </h4>
          <p style="font-size: 0.85rem; margin: 6px 0;"><strong>Sowing Season:</strong> ${c.time}</p>
          <p style="font-size: 0.85rem; margin: 6px 0;"><strong>Water Strategy:</strong> ${c.water} (Source compatibility: ${water})</p>
          
          <div style="background: var(--bg-primary); padding: 12px; border-radius: var(--radius-sm); margin-top: 10px;">
            <p style="font-size: 0.8rem; margin-bottom: 4px;"><strong>NPK Fertilization Schedule:</strong></p>
            <p style="font-size: 0.8rem; color: var(--text-secondary);">${c.fertilizer}</p>
          </div>

          <div style="background: rgba(16, 185, 129, 0.08); border-left: 3px solid var(--primary); padding: 12px; border-radius: var(--radius-sm); margin-top: 10px;">
            <p style="font-size: 0.8rem; margin-bottom: 4px; color: var(--primary-hover);"><strong>Sustainable Organic Best Practice:</strong></p>
            <p style="font-size: 0.8rem; color: var(--text-primary);">${c.organic}</p>
          </div>
        </div>
      `;
    });

    outputDiv.innerHTML = `
      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px;">
        <h3 style="font-family: var(--font-display); font-size: 1.2rem;">Optimized Recommendations for ${soil}</h3>
        <span style="font-size: 0.75rem; background: var(--primary-light); color: var(--primary-hover); padding: 4px 8px; border-radius: 4px; font-weight: 600;">${water}</span>
      </div>
      ${cropsHtml}
    `;

    this.showToast(`Calculated climate crops for ${soil}`, 'success');
  },

  showIrrigationAdvisor: function(type) {
    const outputDiv = document.getElementById('farmResultContent');
    const initialText = document.getElementById('farmResultInitialText');

    initialText.style.display = 'none';
    outputDiv.style.display = 'block';

    if (type === 'drip') {
      outputDiv.innerHTML = `
        <h3 style="font-family: var(--font-display); font-size: 1.2rem; margin-bottom: 12px; color: var(--primary);"><i class="fa-solid fa-droplet"></i> Drip Irrigation Recommendation</h3>
        <p style="font-size: 0.88rem; line-height: 1.6; margin-bottom: 16px;">
          Drip irrigation applies water slowly directly to the crop roots, minimizing evaporation and weed growth. Ideal for row crops (cotton, vegetables, sugarcane, orchards).
        </p>
        <table class="response-table" style="margin-bottom: 16px;">
          <tr><td><strong>Water Saving:</strong></td><td>40% to 70% compared to surface flooding.</td></tr>
          <tr><td><strong>Fertilizer Efficiency:</strong></td><td>Can apply fertilizers directly through water (Fertigation).</td></tr>
          <tr><td><strong>Cost estimate:</strong></td><td>₹40,000 - ₹60,000 per acre (Up to 80% state subsidy is available).</td></tr>
        </table>
        <div style="background: var(--bg-primary); padding: 12px; border-radius: var(--radius-sm); font-size: 0.8rem;">
          <strong>Tip:</strong> Clean the drip filter screens weekly to prevent sand or clay clogging.
        </div>
      `;
    } else {
      outputDiv.innerHTML = `
        <h3 style="font-family: var(--font-display); font-size: 1.2rem; margin-bottom: 12px; color: var(--info);"><i class="fa-solid fa-shower"></i> Sprinkler Irrigation Recommendation</h3>
        <p style="font-size: 0.88rem; line-height: 1.6; margin-bottom: 16px;">
          Sprinklers spray water into the air, creating a rainfall-like effect. Best for closely spaced crops (groundnut, wheat, gram, millets, leafy vegetables).
        </p>
        <table class="response-table" style="margin-bottom: 16px;">
          <tr><td><strong>Water Saving:</strong></td><td>25% to 40% saving. Ideal for sandy soils with high absorption.</td></tr>
          <tr><td><strong>Topography:</strong></td><td>Works well on undulating or sloping fields without land leveling.</td></tr>
          <tr><td><strong>Cost estimate:</strong></td><td>₹18,000 - ₹30,000 for a portable system.</td></tr>
        </table>
        <div style="background: var(--bg-primary); padding: 12px; border-radius: var(--radius-sm); font-size: 0.8rem;">
          <strong>Tip:</strong> Avoid spraying during high midday wind hours to prevent uneven water layout.
        </div>
      `;
    }
  },

  // 4. Entrepreneurship Planner Details
  renderBusinessList: function() {
    const container = document.getElementById('bizCardsContainer');
    container.innerHTML = '';

    this.databases.businesses.forEach((b, index) => {
      const card = document.createElement('div');
      card.className = `biz-card ${index === 0 ? 'active' : ''}`;
      card.onclick = () => this.selectBusiness(b.id, card);

      card.innerHTML = `
        <div class="biz-icon"><i class="fa-solid ${b.icon}"></i></div>
        <div class="biz-info">
          <h4>${b.name}</h4>
          <span>Est. Capital: ${b.investment}</span>
        </div>
      `;
      container.appendChild(card);
    });

    // Load initial detailed card
    this.selectBusiness(this.databases.businesses[0].id);
  },

  selectBusiness: function(id, clickedCard = null) {
    if (clickedCard) {
      document.querySelectorAll('.biz-card').forEach(c => c.classList.remove('active'));
      clickedCard.classList.add('active');
    }

    const b = this.databases.businesses.find(item => item.id === id);
    if (!b) return;

    const details = document.getElementById('bizDetailsCard');
    
    // Risk Class mapping
    const riskClass = b.risk.toLowerCase().includes('high') ? 'high' : 
                      b.risk.toLowerCase().includes('medium') ? 'medium' : 'low';

    details.innerHTML = `
      <div class="biz-header">
        <div class="biz-title-wrap">
          <h3>${b.name}</h3>
          <p><i class="fa-solid fa-bullseye"></i> Goal: Profitable Local Rural Micro-enterprise</p>
        </div>
        <div class="biz-icon" style="background: var(--primary); color: #fff; width:50px; height:50px;"><i class="fa-solid ${b.icon}"></i></div>
      </div>

      <div class="biz-metrics-bar">
        <div class="metric-box">
          <label>Capital Required</label>
          <span style="color: var(--primary-hover);">${b.investment}</span>
        </div>
        <div class="metric-box">
          <label>Profit Range</label>
          <span style="color: var(--success); font-size: 0.85rem;">${b.profit}</span>
        </div>
        <div class="metric-box">
          <label>Risk Level</label>
          <span class="risk-badge ${riskClass}">${b.risk}</span>
        </div>
        <div class="metric-box">
          <label>Market Demand</label>
          <span>High</span>
        </div>
      </div>

      <div class="biz-tabs">
        <button class="biz-tab-btn active" onclick="app.switchBizTab('setup', this)">Startup Roadmap</button>
        <button class="biz-tab-btn" onclick="app.switchBizTab('swot', this)">SWOT Assessment</button>
        <button class="biz-tab-btn" onclick="app.switchBizTab('marketing', this)">Marketing Plan</button>
      </div>

      <!-- Setup tab pane -->
      <div class="biz-tab-pane active" id="biz-tab-pane-setup">
        <p style="margin-bottom: 12px;"><strong>Skills:</strong> ${b.skills}</p>
        <p style="margin-bottom: 16px;"><strong>Equipment:</strong> ${b.equipment}</p>
        <h4 style="font-family: var(--font-display); font-weight: 700; margin-bottom: 8px;">Step-by-Step Launch Guide:</h4>
        <ol style="padding-left: 20px; margin-bottom: 16px;">
          ${b.steps.map(step => `<li style="margin-bottom: 6px;">${step}</li>`).join('')}
        </ol>
        <div style="background: rgba(234, 179, 8, 0.08); border-left: 3px solid var(--accent); padding: 12px; border-radius: var(--radius-sm);">
          <strong>Subsidy & Grant Opportunity:</strong> ${b.subsidies}
        </div>
      </div>

      <!-- SWOT pane -->
      <div class="biz-tab-pane" id="biz-tab-pane-swot">
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px;">
          <div style="background: rgba(34, 197, 94, 0.08); padding: 12px; border-radius: var(--radius-sm);">
            <strong style="color: var(--success);"><i class="fa-solid fa-plus"></i> Strengths</strong>
            <p style="font-size: 0.8rem; margin-top: 4px;">${b.swot.s}</p>
          </div>
          <div style="background: rgba(239, 68, 68, 0.08); padding: 12px; border-radius: var(--radius-sm);">
            <strong style="color: var(--danger);"><i class="fa-solid fa-minus"></i> Weaknesses</strong>
            <p style="font-size: 0.8rem; margin-top: 4px;">${b.swot.w}</p>
          </div>
          <div style="background: rgba(14, 165, 233, 0.08); padding: 12px; border-radius: var(--radius-sm); margin-top: 8px;">
            <strong style="color: var(--info);"><i class="fa-solid fa-chart-line"></i> Opportunities</strong>
            <p style="font-size: 0.8rem; margin-top: 4px;">${b.swot.o}</p>
          </div>
          <div style="background: rgba(234, 179, 8, 0.08); padding: 12px; border-radius: var(--radius-sm); margin-top: 8px;">
            <strong style="color: var(--accent);"><i class="fa-solid fa-shield-cat"></i> Threats</strong>
            <p style="font-size: 0.8rem; margin-top: 4px;">${b.swot.t}</p>
          </div>
        </div>
      </div>

      <!-- Marketing pane -->
      <div class="biz-tab-pane" id="biz-tab-pane-marketing">
        <h4 style="font-family: var(--font-display); font-weight: 700; margin-bottom: 8px;">Target Customers & Channels</h4>
        <p style="margin-bottom: 12px;">${b.marketing}</p>
        <h4 style="font-family: var(--font-display); font-weight: 700; margin-bottom: 8px;">Growth & Scaling Strategy</h4>
        <p>${b.opportunities}</p>
      </div>
    `;
  },

  switchBizTab: function(tabName, clickedBtn) {
    // Toggle active tab button class
    const tabContainer = clickedBtn.parentElement;
    tabContainer.querySelectorAll('.biz-tab-btn').forEach(btn => btn.classList.remove('active'));
    clickedBtn.classList.add('active');

    // Toggle active panel view
    const detailsContainer = tabContainer.parentElement;
    detailsContainer.querySelectorAll('.biz-tab-pane').forEach(pane => pane.classList.remove('active'));
    detailsContainer.querySelector(`#biz-tab-pane-${tabName}`).classList.add('active');
  },

  // 5. Panchayat & NGO Proposal Generation
  generateProposalReport: function() {
    const focus = document.getElementById('proposalCategory').value;
    const village = document.getElementById('proposalTargetVillage').value || 'Gram Vikas Nagar';
    const budget = parseFloat(document.getElementById('proposalBudget').value) || 300000;
    const duration = document.getElementById('proposalDuration').value;
    
    const outputBody = document.getElementById('proposalOutputBody');
    
    // Formatting currency
    const budgetFormatted = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(budget);
    
    let template = '';

    if (focus === 'village_water') {
      template = `
PROJECT PROPOSAL FOR VILLAGE WATER SUPPLY INFRASTRUCTURE

Target Location: Village ${village}
Project Duration: ${duration}
Total Budget Requested: ${budgetFormatted}

1. EXECUTIVE SUMMARY & OBJECTIVE:
This project aims to secure clean drinking water access for all households in Village ${village}. By tapping local groundwater sources via a solar-powered borewell system and piping to communal water taps, the project eliminates rural women having to walk 3km daily for water.

2. DETAILED IMPLEMENTATION SCOPE:
- Borewell digging and hydrologic profiling.
- Erection of a 10,000 Liter elevated steel storage tank.
- Installation of a 3HP solar-powered water pump system.
- Erection of 6 communal water delivery points across wards.

3. BUDGET ESTIMATION & CAPITAL BREAKDOWN:
-----------------------------------------------------------------
Item                                          Estimated Cost (INR)
-----------------------------------------------------------------
Borewell excavation & casing installation     ${(budget * 0.25).toFixed(0)}
10,000L Overhead Water Tank Construction      ${(budget * 0.35).toFixed(0)}
3HP Solar Pump, Panels & Inverter kit         ${(budget * 0.22).toFixed(0)}
Pipeline fitting and street community taps    ${(budget * 0.13).toFixed(0)}
Administrative charges & community audits     ${(budget * 0.05).toFixed(0)}
-----------------------------------------------------------------
TOTAL PROJECT ESTIMATED BUDGET                ${budgetFormatted}
-----------------------------------------------------------------

4. PROJECT TIMELINE & PHASES:
- Month 1-2: Water mapping survey, drilling and solar panel installation.
- Month 3: Pipeline laying, valve connections and test pumping.
- Month 4: Gram Sabha commissioning and water security audit.

5. MONITORING & SUSTAINABILITY INDICATORS:
- Average clean water delivery (target: 40 liters per capita per day).
- Percentage reduction in local water-borne illnesses (target: >60% drop).
- Formation of a village "Paani Samiti" (Water Committee) to collect a monthly ₹30 maintenance fee per family.
      `;
    } else if (focus === 'waste_mgmt') {
      template = `
CSR FUNDING PROPOSAL: COMMUNITY-DRIVEN RURAL SOLID WASTE MANAGEMENT

Target Location: Village ${village}
Project Duration: ${duration}
Total Funding Asked: ${budgetFormatted}

1. EXECUTIVE SUMMARY:
Village ${village} is experiencing open composting issues leading to blocked drainage and health problems. This project implements a solid waste segregation model at source (household level), compost recycling, and clean plastic selling.

2. DETAILED PLAN:
- Distribution of dry/wet waste buckets to 250 village households.
- Construction of 4 concrete aerated vermicomposting pits.
- Setup of a sorting shed and purchase of a waste transport cart.
- Training of local youth as sanitation collectors.

3. PROJECT COST BREAKDOWN:
-----------------------------------------------------------------
Item Description                              Estimated Cost (INR)
-----------------------------------------------------------------
Household segregation bins (500 units)        ${(budget * 0.20).toFixed(0)}
Vermicompost Concrete Pits (4 units)          ${(budget * 0.40).toFixed(0)}
Garbage sorting shed & transport tri-cart     ${(budget * 0.25).toFixed(0)}
Awareness campaigns, flyers and training      ${(budget * 0.10).toFixed(0)}
Project oversight, compliance & signage       ${(budget * 0.05).toFixed(0)}
-----------------------------------------------------------------
TOTAL ESTIMATED PROJECT COST                  ${budgetFormatted}
-----------------------------------------------------------------

4. TIMELINE:
- Month 1-2: Door-to-door waste sorting workshop. Construction of vermi-pits.
- Month 3-4: Collection route starts. First organic compost harvest sold to local farmers.

5. MONITORING INDICATORS:
- Total tonnage of compost generated and sold to crop fields.
- Number of households achieving 100% waste segregation.
      `;
    } else if (focus === 'renew_energy') {
      template = `
PROJECT REPORT: VILLAGE SOLAR STREET LIGHTING & MINI-GRID SYSTEM

Target Location: Village ${village}
Project Duration: ${duration}
Funding Needed: ${budgetFormatted}

1. EXECUTIVE SUMMARY:
Provide solar lighting at public centers (health clinic, school paths, and village junction) in ${village} to improve evening safety and enable community meetings after dark.

2. SYSTEM DESIGN & SCOPE:
- Erection of 12 standalone 12W LED solar streetlights with lithium battery backup.
- Setup of a 2kW solar charging station at the Panchayat Bhavan for emergency cell phone charging and basic power.

3. BUDGET SPREAD:
-----------------------------------------------------------------
Item Details                                  Estimated Cost (INR)
-----------------------------------------------------------------
Standalone LED solar streetlights (12 posts)  ${(budget * 0.60).toFixed(0)}
Solar solar charging station (2kW grid kit)   ${(budget * 0.25).toFixed(0)}
Civil work, foundations, and battery housing  ${(budget * 0.10).toFixed(0)}
Operator training & maintenance tools         ${(budget * 0.05).toFixed(0)}
-----------------------------------------------------------------
TOTAL ESTIMATED OUTLAY                        ${budgetFormatted}
-----------------------------------------------------------------

4. IMPACT EVALUATION:
- Zero carbon footprint, zero electricity billing for the Panchayat.
- Enhanced night hours for local small shops.
      `;
    } else {
      template = `
NGO GRANT APPLICATION: SKILL TRAINING & LIVELIHOOD CENTER FOR YOUTH

Target Location: Sub-district surrounding Village ${village}
Project Duration: ${duration}
Total Grant Request: ${budgetFormatted}

1. PROJECT AIM:
Empower rural school dropouts and women with livelihood skills (Tailoring, basic computer usage, mobile repair, and micro-business management).

2. KEY DELIVERABLES:
- Renovation of a rented classroom as a Livelihood Center.
- Purchase of 5 sewing machines, 3 desktop PCs, and toolkits.
- Direct certification for 60 youths per year.

3. DETAILED FINANCIALS:
-----------------------------------------------------------------
Item                                          Estimated Cost (INR)
-----------------------------------------------------------------
Sewing machines and computer devices          ${(budget * 0.50).toFixed(0)}
Trainer honorarium and course books           ${(budget * 0.30).toFixed(0)}
Center rent & electricity setup               ${(budget * 0.15).toFixed(0)}
Placement support and certification prints    ${(budget * 0.05).toFixed(0)}
-----------------------------------------------------------------
TOTAL REQUESTED FUNDS                         ${budgetFormatted}
-----------------------------------------------------------------

4. TIMELINE:
- Month 1: Center setup & hardware installations.
- Month 2-5: First batch course running.
- Month 6: Placement drive.
      `;
    }

    outputBody.textContent = template;
    this.showToast('Project proposal compiled successfully.', 'success');
  },

  // 6. Disaster resilience center checklists
  renderDisasterDetails: function(hazard) {
    const card = document.getElementById('disasterDetailsCard');
    
    if (hazard === 'flood') {
      card.innerHTML = `
        <div style="display:flex; justify-content:space-between; align-items:center; border-bottom:1px solid var(--border-color); padding-bottom:16px; margin-bottom:16px;">
          <h3 style="font-family:var(--font-display); font-size:1.2rem; color:var(--danger);"><i class="fa-solid fa-cloud-showers-water"></i> Flood & Cyclone Emergency Prep</h3>
          <span style="font-size:0.75rem; background:rgba(239,68,68,0.1); color:var(--danger); padding:4px 8px; border-radius:4px; font-weight:600;">Active Hazard</span>
        </div>

        <div class="disaster-phase-tabs">
          <button class="disaster-phase-btn active" onclick="app.switchDisasterPhase('prep', this)">1. Preparation (Before)</button>
          <button class="disaster-phase-btn" onclick="app.switchDisasterPhase('resp', this)">2. Emergency Response (During)</button>
          <button class="disaster-phase-btn" onclick="app.switchDisasterPhase('rec', this)">3. Recovery (After)</button>
        </div>

        <div class="disaster-phase-pane active" id="disaster-pane-prep">
          <ul class="disaster-checklist">
            <li><input type="checkbox"> <span>Identify high-ground shelters in the village (e.g. concrete school building).</span></li>
            <li><input type="checkbox"> <span>Store dry food grains, clean drinking water, flashlights, and extra batteries in plastic bags.</span></li>
            <li><input type="checkbox"> <span>Move livestock and farm cattle to elevated areas. Untie them if flooding is imminent.</span></li>
            <li><input type="checkbox"> <span>Seal personal documents (Aadhaar, Land deeds, Bank passbook) in waterproof plastic pouches.</span></li>
          </ul>
        </div>

        <div class="disaster-phase-pane" id="disaster-pane-resp">
          <ul class="disaster-checklist">
            <li><input type="checkbox" checked disabled> <span>Disconnect main power lines and gas cylinders to avoid electrocution/fires.</span></li>
            <li><input type="checkbox"> <span>Do NOT drive or walk through flood waters. A depth of 6 inches can sweep away humans.</span></li>
            <li><input type="checkbox"> <span>Listen to regional weather updates via battery-powered radios.</span></li>
          </ul>
        </div>

        <div class="disaster-phase-pane" id="disaster-pane-rec">
          <ul class="disaster-checklist">
            <li><input type="checkbox"> <span>Sprinkle bleaching powder/lime in waterlogged yard areas to prevent disease vectors.</span></li>
            <li><input type="checkbox"> <span>Boil all drinking water to prevent cholera and gastrointestinal outbreaks.</span></li>
            <li><input type="checkbox"> <span>File claims under PM Fasal Bima Yojana within 72 hours of crop damage. Take geotagged photos.</span></li>
          </ul>
        </div>

        <div style="margin-top:20px; background:var(--bg-primary); padding:16px; border-radius:var(--radius-md); font-size:0.85rem; border-left:4px solid var(--danger);">
          <strong>National Emergency Helpline:</strong> Dial <strong>1070</strong> or State Disaster Helpline <strong>1078</strong>.
        </div>
      `;
    } else if (hazard === 'drought') {
      card.innerHTML = `
        <div style="display:flex; justify-content:space-between; align-items:center; border-bottom:1px solid var(--border-color); padding-bottom:16px; margin-bottom:16px;">
          <h3 style="font-family:var(--font-display); font-size:1.2rem; color:var(--accent);"><i class="fa-solid fa-temperature-arrow-up"></i> Dry Spells & Drought Strategy</h3>
          <span style="font-size:0.75rem; background:var(--accent-light); color:var(--accent); padding:4px 8px; border-radius:4px; font-weight:600;">Mitigation Plan</span>
        </div>

        <div class="disaster-phase-tabs">
          <button class="disaster-phase-btn active" onclick="app.switchDisasterPhase('prep', this)">1. Water Conservation</button>
          <button class="disaster-phase-btn" onclick="app.switchDisasterPhase('resp', this)">2. Crop Management</button>
          <button class="disaster-phase-btn" onclick="app.switchDisasterPhase('rec', this)">3. Government Assistance</button>
        </div>

        <div class="disaster-phase-pane active" id="disaster-pane-prep">
          <ul class="disaster-checklist">
            <li><input type="checkbox"> <span>Implement plastic/organic mulching to cover soil and prevent root-zone evaporation.</span></li>
            <li><input type="checkbox"> <span>Clean and restore village community farm ponds to harvest minor showers.</span></li>
            <li><input type="checkbox"> <span>Transition high-water consumption crops (like sugarcane) into low-water millets/pulses.</span></li>
          </ul>
        </div>

        <div class="disaster-phase-pane" id="disaster-pane-resp">
          <ul class="disaster-checklist">
            <li><input type="checkbox"> <span>Irrigate fields strictly in the late evening or early morning hours.</span></li>
            <li><input type="checkbox"> <span>Use foliar sprays of 1% Potassium Chloride to help plants tolerate moisture stress.</span></li>
          </ul>
        </div>

        <div class="disaster-phase-pane" id="disaster-pane-rec">
          <ul class="disaster-checklist">
            <li><input type="checkbox"> <span>Request drought declaration surveys from the local Taluka agricultural officer.</span></li>
            <li><input type="checkbox"> <span>Utilize MGNREGA employment options for building farm bunds during off-season.</span></li>
          </ul>
        </div>
      `;
    } else {
      card.innerHTML = `
        <div style="display:flex; justify-content:space-between; align-items:center; border-bottom:1px solid var(--border-color); padding-bottom:16px; margin-bottom:16px;">
          <h3 style="font-family:var(--font-display); font-size:1.2rem; color:var(--primary-hover);"><i class="fa-solid fa-bug"></i> Pest / Disease Outbreak Resilience</h3>
          <span style="font-size:0.75rem; background:var(--primary-light); color:var(--primary-hover); padding:4px 8px; border-radius:4px; font-weight:600;">Crops & Livestock</span>
        </div>

        <div class="disaster-phase-tabs">
          <button class="disaster-phase-btn active" onclick="app.switchDisasterPhase('prep', this)">1. Prevention</button>
          <button class="disaster-phase-btn" onclick="app.switchDisasterPhase('resp', this)">2. Containment</button>
          <button class="disaster-phase-btn" onclick="app.switchDisasterPhase('rec', this)">3. Bio-Remedies</button>
        </div>

        <div class="disaster-phase-pane active" id="disaster-pane-prep">
          <ul class="disaster-checklist">
            <li><input type="checkbox"> <span>Conduct regular scouting (walk diagonal paths across crop field once a week).</span></li>
            <li><input type="checkbox"> <span>Hang yellow sticky pheromone traps to monitor presence of whiteflies and aphids.</span></li>
          </ul>
        </div>

        <div class="disaster-phase-pane" id="disaster-pane-resp">
          <ul class="disaster-checklist">
            <li><input type="checkbox"> <span>In case of severe attack, isolate affected crop fields. Cut and bury highly infested leaves.</span></li>
            <li><input type="checkbox"> <span>Form community village groups to spray fields simultaneously, preventing pest migration.</span></li>
          </ul>
        </div>

        <div class="disaster-phase-pane" id="disaster-pane-rec">
          <ul class="disaster-checklist">
            <li><input type="checkbox"> <span>Spray Neem oil mixed with soap water for a low-cost, organic insect deterrent.</span></li>
            <li><input type="checkbox"> <span>Apply Trichoderma powder mixed with farm compost to solve soil fungus outbreaks.</span></li>
          </ul>
        </div>
      `;
    }
  },

  switchDisasterPhase: function(phaseName, clickedBtn) {
    const tabContainer = clickedBtn.parentElement;
    tabContainer.querySelectorAll('.disaster-phase-btn').forEach(btn => btn.classList.remove('active'));
    clickedBtn.classList.add('active');

    const detailsContainer = tabContainer.parentElement;
    detailsContainer.querySelectorAll('.disaster-phase-pane').forEach(pane => pane.classList.remove('active'));
    detailsContainer.querySelector(`#disaster-pane-${phaseName}`).classList.add('active');
  }
};

// Start application when DOM loads
window.addEventListener('DOMContentLoaded', () => {
  app.init();
});
